<?php
// $Id$

/**
 * @file
 * Custom Functions
 */

 function follow_custom_follow_networks_alter(&$networks, $uid = 0) {
   //Add a network.
   $networks[$uid]['imdb'] = array(
    'title' => t('IMDB'),
    'domain' => 'imdb.com',
   );

  $networks[$uid]['drupal'] = array(
    'title' => t('Drupal.org'),
    'domain' => 'drupal.org',
  );

  $networks[$uid]['etsy'] = array(
    'title' => t("Jamie's Etsy shop"),
    'domain' => 'etsy.com',
  );
 }
